name: Docs

# This GitHub Action sets up a workflow to deploy documentation.
# It utilizes the actions/checkout action to fetch the codebase and the
# peaceiris/actions-gh-pages action to deploy a directory.
# TODO: Make action that copy yaml file and contain a template! Now it just copy
# the docs folder to the gh-pages.
# https://github.com/peaceiris/actions-gh-pages
on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
