name: Lint

on:
  push:
    branches:
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "staging"]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint api
        uses: github/super-linter@v4
        env:
          #VALIDATE_ALL_CODEBASE: false
          VALIDATE_OPENAPI: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
